### ISSUE TITLE
Service Mode does not end Drive in Progress.

### ISSUE THREAD

**Issue by LelandSindt** [adriankumpf/teslamate#593]
**Describe the bug**

An in progress drive is not terminated when the car is put into service mode.

**To Reproduce**

1. Take your car in for service.. :)

**Expected behavior**

An in progress drive would be terminated when Service mode is enabled. 

**Relevant entries from the logs**
```
20:44:07.031 car_id=1 [info] Driving / Start
20:44:07.509 [error] TeslaApi.Error / 405 – %{
  "error" => "vehicle is curently in service",
  "error_description" => "",
  "response" => nil
}
20:44:07.509 car_id=1 [info] Vehicle is currently in service
20:44:13.533 car_id=1 [info] Fetch already in progress ...
20:44:13.703 [error] TeslaApi.Error / 405 – %{
  "error" => "vehicle is curently in service",
  "error_description" => "",
  "response" => nil
}
20:44:13.703 car_id=1 [info] Vehicle is currently in service
20:44:13.885 [error] TeslaApi.Error / 405 – %{
  "error" => "vehicle is curently in service",
  "error_description" => "",
  "response" => nil
}
```
.... repeats every few seconds...

**Operating environment**

- TeslaMate Version:  v1.19.0 - dev
- Type of installation: kubernetes  https://github.com/LelandSindt/teslamate/blob/master/manifest.yaml
- OS: Ubuntu

**Comment by adriankumpf** [comment]
It is always fascinating to see what edge cases there are :) Fixed in 79d7076402df54674067f60102f1e73db3740131

**Comment by Fatal705** [comment]
I experience the same issue with v1.22.0 running on docker. After bringing my tesla into service, it still shows as driving.

Log entries:
```
2021-04-06 13:35:06.587 car_id=1 [info] Start / :online
2021-04-06 13:42:20.152 car_id=1 [info] Driving / Start
2021-04-06 13:42:20.502 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/XXXXXXXXX/vehicle_data -> 405 (239.150 ms)
2021-04-06 13:42:20.504 [warn] TeslaApi.Error / %{
  "error" => "vehicle is currently in service", 
  "error_description" => "", 
  "response" => nil
}
2021-04-06 13:42:20.505 car_id=1 [error] Error / :unknown
```
The last 3 entries are repeated approximately every 10 seconds.
